[package]
name = "repo2txt-r"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.7"
ignore = "0.4.22"
serde_json = "1.0.117"
serde = { version = "1.0.203", features = ["derive"] }
serde_derive = "1.0"