name: Tests and release

on:
  push:
    tags:
      - "v*"

env:
  CRATE_NAME: repo2txt-r
  GITHUB_TOKEN: ${{ github.token }}
  RUST_BACKTRACE: 1

jobs:
  test:
    name: ${{ matrix.os_name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os_name: [FreeBSD-x86_64, Linux-x86_64, Linux-aarch64, Linux-arm, Linux-i686, Linux-powerpc, Linux-powerpc64, Linux-powerpc64le, Linux-riscv64, Linux-s390x, NetBSD-x86_64, Windows-aarch64, Windows-i686, Windows-x86_64, macOS-x86_64, macOS-aarch64]
        os: [ubuntu-20.04, windows-latest, macOS-latest]
        target: [x86_64-unknown-freebsd, x86_64-unknown-linux-musl, aarch64-unknown-linux-musl, arm-unknown-linux-musleabi, i686-unknown-linux-musl, powerpc-unknown-linux-gnu, powerpc64-unknown-linux-gnu, powerpc64le-unknown-linux-gnu, riscv64gc-unknown-linux-gnu, s390x-unknown-linux-gnu, x86_64-unknown-netbsd, aarch64-pc-windows-msvc, i686-pc-windows-msvc, x86_64-pc-windows-msvc, x86_64-apple-darwin, aarch64-apple-darwin]
        bin: [repo2txt-r, repo2txt-r.exe]
        toolchain: [stable, beta, nightly]
        include:
          - os_name: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            bin: repo2txt-r
          - os_name: Linux-aarch64
            os: ubuntu-20.04
            target: aarch64-unknown-linux-musl
            bin: repo2txt-r
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: repo2txt-r.exe
          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: repo2txt-r
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Configure Git
        run: |
          git config --global user.email "jdoe@example.com"
          git config --global user.name "J. Doe"
      - name: Install musl-tools on Linux
        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools
        if: contains(matrix.target, 'musl')
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--release"
          strip: true
      - name: Run tests
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "test"
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--release"
        if: ${{ matrix.toolchain != 'stable' || !contains(['FreeBSD-x86_64', 'Linux-i686', 'Linux-powerpc', 'Linux-powerpc64', 'Linux-powerpc64le', 'Linux-s390x', 'NetBSD-x86_64', 'Windows-aarch64', 'Windows-i686', 'macOS-aarch64'], matrix.os) }}
      - name: Package as archive
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            7z a ../../../repo2txt-r-${{ matrix.os_name }}.zip ${{ matrix.bin }}
          else
            tar czvf ../../../repo2txt-r-${{ matrix.os_name }}.tar.gz ${{ matrix.bin }}
          fi
          cd -
        if: |
          matrix.toolchain == 'stable' &&
          ( github.ref_name == 'refs/tags/test-release' || startsWith(github.ref, 'refs/tags/v') )
      - name: Publish release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: repo2txt-r-${{ matrix.os_name }}
          path: "repo2txt-r-${{ matrix.os_name }}.*"
        if: matrix.toolchain == 'stable' && github.ref == 'refs/tags/test-release'
      - name: Generate SHA-256
        run: shasum -a 256 repo2txt-r-${{ matrix.os_name }}.*
        if: |
          matrix.toolchain == 'stable' &&
          matrix.os == 'macOS-latest' &&
          ( startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/tags/test-release' )
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: "repo2txt-r-${{ matrix.os_name }}.*"
          body_path: Changes.md
        if: matrix.toolchain == 'stable' && startsWith(github.ref, 'refs/tags/v')
